name: "yumeiyue's blog"
description: "yumeiyue的博客"

avatar: https://utop25.github.io/images/profile.png
favicon: https://utop25.github.io/images/favicon.ico

navigation:
  - name: 最近更新
    url: /
  - name: 关于我
    url: /about
  - name: 我的博客
    url: /tags

paginate: 8

excerpt_separator: <!-- more -->

footer-links:
  zhihu: meng-ke-89-15
  email: allenmeng97@gmail.com
  facebook: meng.allen.54
  github: mengke25
  rss: # just type anything here for a working RSS icon
  twitter: mengke1997
  youtube:

footer-text: Copyright (c) 2024 Mengke

url: https://utop25.github.io/

permalink: /:title/
paginate_path: /page:num/

# The release of Jekyll Now
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
